# Based on:
# https://profy.dev/article/continuous-integration-with-github-actions

name: Frontend CI

on:
  # runs on pushes to the main branch
  push:
    branches: [main]
  # also runs inside pull requests that target the main branch
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./frontend

jobs:
  frontend:
    # uses a Ubuntu Docker image (like a virtual machine)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      # install dependencies
      - run: npm ci
      # run ESLint
      - run: npm run lint
      # verify that there are no build errors
      - run: npm run build

      # TODO: Run tests with jest too.

      # run tests with Cypress
      # TODO: Make tests pass and then reactivate.
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: npm start